# Dynamic inventory using AWS
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  "tag:Project": "rh-enterprise-cloud-lab"
  "tag:Environment": "dev"
compose:
  ansible_host: private_ip_address    # connect to private IPs (we'll ProxyJump via bastion)
keyed_groups:
  - key: tags.Role
    prefix: role                      # creates groups: role_ansible, role_eda, role_rhel, role_satellite
hostnames:
  - private-ip-address
  - tags.Name
strict: False

